name: Frontend CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  ci:
    name: CI - Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install
      working-directory: mustep-fe

    - name: Create .env file
      run: echo "${{ secrets.ENV_FILE }}" > .env
      working-directory: mustep-fe

    - name: Build Vite project
      run: npm run build
      working-directory: mustep-fe

    - name: Docker build
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/9roomthon-4-team-fe:latest -f ../Dockerfile .
      working-directory: mustep-fe

    - name: Docker Hub login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Docker push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/9roomthon-4-team-fe:latest

  cd:
    name: CD - Deploy to EC2
    needs: ci
    runs-on: ubuntu-latest

    steps:
    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/9roomthon-4-team-fe:latest
          docker-compose -f docker-compose.yml down
          docker-compose -f docker-compose.yml up -d --build
